### ISSUE TITLE
BRF icon braille 'b' is wrong

### ISSUE THREAD

**Issue by wesinator** [hapticallyspeaking/braille-ready-format-and-pdf-icon#1]
The bottom dot of the `b` should be in the middle. It currently looks like a braille `k`
https://en.wikipedia.org/wiki/English_Braille#Alphabet

**Comment by fhightower** [comment]
Thanks for reporting this!

**Comment by wesinator** [comment]
This seems to have greyed the black icon, by the way - https://github.com/hapticallyspeaking/braille-ready-format-and-pdf-icon/commit/e27693960d66485390325d8134ec463d94a144b8#diff-f40a562efdbde53d62a128c90bb12176
Could you move the dot on the bitmap of https://raw.githubusercontent.com/hapticallyspeaking/braille-ready-format-and-pdf-icon/a60eaac715d6d5298e3b88052cb5923e2d98b021/braille_ready_format/black/brf.png ?

**Comment by fhightower** [comment]
Thanks for the heads up. These are fine in their current state although PR's are certainly accepted.
